### ISSUE TITLE
Inconsistent/wrong :ref

### ISSUE THREAD

**Issue by ad-clearhaus** [clearhaus/3DSv2-api-documentation#20]
Looking at https://docs.3dsecure.io/3dsv2/getting-started.html, references that point to either `2.1.0` or `2.2.0` are linking wrong or are in them self textually wrong.

![Screenshot from 2022-11-02 10-43-34](https://user-images.githubusercontent.com/24522411/199457702-482aaae8-bfa3-4815-93fb-49497c58d1fd.png)
![Screenshot from 2022-11-02 10-35-30](https://user-images.githubusercontent.com/24522411/199457709-979465fe-4e3a-422e-a3eb-f8164a0ac975.png)

**Comment by thejspr** [comment]
Fixed in upcoming v2.3.1 docs update
