### ISSUE TITLE
acctType needs possible values documented

### ISSUE THREAD

**Issue by dvaeversted** [clearhaus/3DSv2-api-documentation#6]
In the documentation, the different possible values are not documented.

![image](https://user-images.githubusercontent.com/1611810/77561597-37ab3f00-6ebf-11ea-9312-ff9f938d6be3.png)

**Comment by kse-clearhaus** [comment]
Fixed by: https://github.com/clearhaus/3DSv2-api-documentation/commit/123f94ea38e3af81483ecf2f8068d780881e50a3
