### ISSUE TITLE
Broken link on threeDSRequestorAuthenticationInfo

### ISSUE THREAD

**Issue by dvaeversted** [clearhaus/3DSv2-api-documentation#8]
In the reference for the auth endpoint, the link points to https://clearhaus.github.io/3DSv2-api-documentation/reference.html?messageCategory=P&deviceChannel=BRW#threedsrequestorauthenticationinfo210 which is not found.

Should most likely be https://clearhaus.github.io/3DSv2-api-documentation/reference.html?messageCategory=P&deviceChannel=BRW#threedsrequestorauthenticationinfo instead :-)

**Comment by kse-clearhaus** [comment]
Fixed by: https://github.com/clearhaus/3DSv2-api-documentation/commit/8cb3cd9f4b32b1e0f7a2bcd5c06141823fdc7cf4

The reference is automatically generated from another source. This had some inconsistencies in it :)
