### ISSUE TITLE
billAddrCountry and shipAdddrCountry format not mentioned

### ISSUE THREAD

**Issue by dvaeversted** [clearhaus/3DSv2-api-documentation#9]
These 2 fields are only documented as being 3 characters long string, however it would be relevant to mention that the ISO-3166-1 numeric three-digit country code is expected.

**Comment by kse-clearhaus** [comment]
Fixed by: https://github.com/clearhaus/3DSv2-api-documentation/commit/ed884e9e3aa9024eafe987dd2e6452c476ee0a2b

Stray comma removed by: https://github.com/clearhaus/3DSv2-api-documentation/commit/d63e1448f3ea92503ae8ae9fc7de0ca6f81a7738
